"""Add column to tables

Revision ID: ca1195a15f6c
Revises: d4a6a5a969cb
Create Date: 2025-10-29 12:50:57.477905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca1195a15f6c'
down_revision: Union[str, Sequence[str], None] = 'd4a6a5a969cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilitymaster', 'userid_fk')
    op.add_column('categorymaster', sa.Column('userid_fk', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_categorymaster_name'), table_name='categorymaster')
    op.create_index(op.f('ix_categorymaster_name'), 'categorymaster', ['name'], unique=True)
    op.add_column('commonmaster', sa.Column('userid_fk', sa.Integer(), nullable=True))
    op.add_column('productsandservices', sa.Column('userid_fk', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_productsandservices_name'), table_name='productsandservices')
    op.create_index(op.f('ix_productsandservices_name'), 'productsandservices', ['name'], unique=True)
    op.add_column('usergroup', sa.Column('capabilitymaster_fk', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usergroup', 'capabilitymaster_fk')
    op.drop_index(op.f('ix_productsandservices_name'), table_name='productsandservices')
    op.create_index(op.f('ix_productsandservices_name'), 'productsandservices', ['name'], unique=False)
    op.drop_column('productsandservices', 'userid_fk')
    op.drop_column('commonmaster', 'userid_fk')
    op.drop_index(op.f('ix_categorymaster_name'), table_name='categorymaster')
    op.create_index(op.f('ix_categorymaster_name'), 'categorymaster', ['name'], unique=False)
    op.drop_column('categorymaster', 'userid_fk')
    op.add_column('capabilitymaster', sa.Column('userid_fk', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
