"""Add tag column to transaction

Revision ID: d4a6a5a969cb
Revises: f2c837cd7941
Create Date: 2025-10-14 15:16:37.281835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a6a5a969cb'
down_revision: Union[str, Sequence[str], None] = 'f2c837cd7941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('userid_fk', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'userid_fk')
    # ### end Alembic commands ###
