"""Add tag column to categorymaster

Revision ID: f2c837cd7941
Revises: 
Create Date: 2025-10-14 15:09:51.521581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c837cd7941'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categorymaster', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('categorymaster', 'commonmaster_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('commonmaster', sa.Column('tag', sa.String(), nullable=True))
    op.alter_column('commonmaster', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('productsandservices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('productsandservices', 'categorymaster_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('transactions', 'products_services_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transactions', 'products_services_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('productsandservices', 'categorymaster_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('productsandservices', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('commonmaster', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('commonmaster', 'tag')
    op.alter_column('categorymaster', 'commonmaster_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categorymaster', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
